# m h  dom mon dow   command
*/5 * * * * /usr/local/bin/webcampak stats collect
*/5 * * * * /usr/local/bin/webcampak xfer start
*/10 * * * * /usr/local/bin/webcampak xfer dispatch
* * * * * php /home/webcampak/webcampak/apps/api/Symfony/3.0/bin/console wpak:alerts
* 6 * * * php /home/webcampak/webcampak/apps/api/Symfony/3.0/bin/console wpak:dailyreport
* 6 * * * php /home/webcampak/webcampak/apps/api/Symfony/3.0/bin/console wpak:runsyncreports
* * * * * php /home/webcampak/webcampak/apps/api/Symfony/3.0/bin/console wpak:sendemails 20


