imports:
    - { resource: param_general.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: extMethodsConfig.php }
    - { resource: param_authorization.yml }
    - { resource: param_paths.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "/home/webcampak/webcampak/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['php', 'twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    serializer:
        enabled: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        #path: "/home/webcampak/webcampak/resources/database/webcampak.db"
        charset: UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: false

        mappings:
            default:
                type: annotation
                dir: %kernel.root_dir%/../src/AppBundle/Entities/Database
                prefix: AppBundle\Entities\Database
                alias: AppBundle

services:
    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.ip%%] [%%extra.token%%] [%%extra.memory%%M] %%channel%%.%%level_name%%: %%message%%\n"

    monolog.processor.session_request:
        class: AppBundle\SessionRequestProcessor
        arguments:  ['@session', '@request_stack']
        tags:
            - { name: monolog.processor, method: processRecord }

    kernel.listener.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ['@monolog.logger', '@session']
        #arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

monolog:
    handlers:
        main:
            type: stream
            #path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            formatter: monolog.formatter.session_request
        console:
            type: console
            verbosity_levels:
                VERBOSITY_NORMAL: INFO