imports:
    - { resource: param_general.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: extMethodsConfig.php }
    - { resource: param_authorization.yml }
    - { resource: param_paths.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "/home/webcampak/webcampak/etc/symfony/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['php', 'twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    serializer:
        enabled: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
#assetic:
#    debug:          "%kernel.debug%"
#    use_controller: false
#    bundles:        [ ]
    #java: /usr/bin/java
#    filters:
#        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        #path: "/home/webcampak/webcampak/resources/database/webcampak.db"
        charset: UTF8

#doctrine:
#    dbal:
#        driver:   "%database_driver%"
#        host:     "%database_host%"
#        port:     "%database_port%"
#        dbname:   "%database_name%"
#        user:     "%database_user%"
#        password: "%database_password%"
#        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: false

        mappings:
            default:
                type: annotation
                dir: %kernel.root_dir%/../src/AppBundle/Entities/Database
                prefix: AppBundle\Entities\Database
                alias: AppBundle

services:
    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.ip%%] [%%extra.token%%] [%%extra.memory%%M] %%channel%%.%%level_name%%: %%message%%\n"

    monolog.processor.session_request:
        class: AppBundle\SessionRequestProcessor
        arguments:  ['@session', '@request_stack']
        tags:
            - { name: monolog.processor, method: processRecord }

    kernel.listener.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ['@monolog.logger', '@session']
        #arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

monolog:
    handlers:
        main:
            type: stream
            #path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            formatter: monolog.formatter.session_request
        console:
            type: console
            verbosity_levels:
                VERBOSITY_NORMAL: INFO