# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entities\Database\Users:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: AppBundle:Users}

    firewalls:
        secured_area:
            remember_me:
              secret:      "%secret%"
              lifetime: 31536000
              path: /
              domain: ~
            pattern:    ^/
            anonymous: ~
            form_login:
              login_path:   login
              check_path:   login_check
              default_target_path: /desktop
              always_use_default_target_path: true
              failure_path: /login?failure=1
            logout:
              path: /logout
              target: /../../

    access_control:
#        - { path: ^/direct/router, roles: ROLE_USER }
# Support multiple IPs, for example  ips: [127.0.0.1, ::1]
        - { path: ^/att, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 10.0.1.179 }
        - { path: ^/att, roles: ROLE_NO_ACCESS }
#        - { path: ^/desktop, roles: ROLE_USER }
